// client-react/src/pages/Notes.tsx
import React, { useEffect, useState } from "react";
import { getNotes } from "../api/notes";
import { CreateNote } from "../components/notes/CreateNote";
import { Outlet, useNavigate } from "react-router-dom";

// Component for the Notes page
export const Notes: React.FC = () => {
  const [notes, setNotes] = useState<any[]>([]);
  const navigate = useNavigate();
  useEffect(() => {
    getNotes().then((res) => {
      setNotes(res);
    });
  }, []);
  return (
    <>
      <div className="py-4">
        <div className="flex items-center justify-between">
          <h1 className="text-2xl font-bold">Notes</h1>
          {notes.length > 0 && <CreateNote />}
        </div>
        <div className="grid sm:grid-cols-2 md:grid-cols-3 gap-2 pt-8">
          {notes &&
            notes.map((note) => (
              <div
                onClick={() => {
                  navigate(`/notes/${note._id}`);
                }}
                className="border border-text rounded-md p-2"
                key={note._id}
              >
                <div className="h-72 w-full overflow-hidden">
                  {note.content ? (
                    note.content
                  ) : (
                    <div className="flex items-center justify-center h-full">
                      <p className="text-text text-sm">Click to add content</p>
                    </div>
                  )}
                </div>
                <h2 className="text-lg text-text font-bold capitalize">
                  {note.title}
                </h2>
              </div>
            ))}
        </div>
        {notes.length === 0 && (
          <div className="flex flex-col gap-2 justify-center items-center h-full">
            <p className="text-text text-sm">No notes found</p>
            <CreateNote />
          </div>
        )}
      </div>
      <Outlet />
    </>
  );
};

// client/src/views/Notes.vue
<template>
  <div class="h-full bg-white">
    {{ notes }}
    <div v-if="notes.length > 0">
      <h1>Notes</h1>
    </div>
    <div v-else class="h-full flex flex-col items-center justify-center">
      <h1 class="text-2xl font-bold">Create your first note</h1>
      <Modal title="Create Note">
        <template #modal-trigger="{ toggleModal }">
          <button @click="toggleModal" class="text-primary p-2 rounded-md flex items-center gap-2">
            <Plus />
            Create Note
          </button>
        </template>
        <template #modal-content="{ toggleModal }">
          <div>
            <input type="text" v-model="title" class="w-full p-2 rounded-md border border-gray-300" placeholder="Note Title" />

            <div class="mt-4 flex justify-end">
              <button @click="toggleModal" class="bg-primary text-white px-4 py-2 rounded-md">
                Create
              </button>
            </div>
          </div>
        </template>
      </Modal>
    </div>
  </div>
</template>

<script setup lang="ts">
import { reactive, onMounted, inject, ref } from 'vue';
import Plus from "vue-material-design-icons/Plus.vue"
import Modal from "../components/Reusable/Modal.vue"

const $api = inject('$api') as any;
const notes = reactive([]);
const title = ref('');


const fetchNotes = async () => {
  try {
    const response = await $api.get('/notes');
    Object.assign(notes, response.data);
  } catch (error) {
    console.error(error);
  }
};

const createNote = async () => {
  try {
    const response: any = await $api.post('/notes', { title: title.value });
    // notes.push(response.data);
  } catch (error) {
    console.error(error);
  }
};

onMounted(async () => {
  await fetchNotes();
});
</script>

<style scoped></style>
