// client-react/src/components/ui/Modal.tsx
"use client";
import { useState } from "react";
import Button from "./Button";

interface ModalProps {
  activator?: React.ReactNode;
  content?: React.ReactNode;
  onToggle?: (isOpen: boolean, toggle: () => void) => void;
}

export const Modal: React.FC<ModalProps> = ({
  activator,
  content,
  onToggle,
}) => {
  const [isOpen, setIsOpen] = useState(false);

  const toggleModal = () => {
    setIsOpen((prev) => !prev);
    if (onToggle) {
      onToggle(!isOpen, toggleModal);
    }
  };

  return (
    <>
      {activator && <div onClick={toggleModal}>{activator}</div>}
      {!activator && <Button onClick={toggleModal}>Modal</Button>}

      {isOpen && (
        <div className="fixed inset-0 z-10 flex items-center justify-center p-4 bg-gray-500 bg-opacity-75">
          <div className="relative w-full max-w-lg bg-white rounded-lg shadow-xl sm:my-8">
            <div className="px-4 pt-5 pb-4 sm:p-6 sm:pb-4">{content}</div>
            {/* <div className="bg-gray-50 px-4 py-3 sm:flex sm:flex-row-reverse sm:px-6"></div> */}
          </div>
        </div>
      )}
    </>
  );
};

// client/src/components/Reusable/Modal.vue
<template>
  <div>
    <slot name="modal-trigger" :toggleModal="toggleModal"></slot>
    <transition name="fade">
      <div v-if="isOpen" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center"
        @click.self="toggleModal">
        <div class="bg-white p-6 rounded-lg shadow-lg w-96">
          <h2 class="text-xl font-bold mb-4">{{ title }}</h2>
          <div>
            <slot name="modal-content" :toggleModal="toggleModal"></slot>
          </div>
        </div>
      </div>
    </transition>
  </div>
</template>

<script setup lang="ts">
import { ref } from "vue";

defineProps({
  title: {
    type: String,
    required: true
  },
});

const isOpen = ref(false);

const toggleModal = () => {
  isOpen.value = !isOpen.value;
};
</script>

<style>
/* Tailwind CSS transition for fade effect */
.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.3s;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
</style>
