// client/src/components/Reusable/Dropdown.vue
<template>
    <div v-click-outside class="dropdown relative inline-block text-left">
        <!-- <div class="dropdown-button" @click="toggleDropdown"> -->
        <slot name="dropdown-trigger" :toggleDropdown="toggleDropdown"></slot>
        <!-- </div> -->
        <Transition name="dropdown" enter-active-class="transition transform duration-200 ease-out"
            enter-from-class="opacity-0 scale-95" enter-to-class="opacity-100 scale-100"
            leave-active-class="transition transform duration-150 ease-in" leave-from-class="opacity-100 scale-100"
            leave-to-class="opacity-0 scale-95">
            <div v-if="isOpen" :class="['absolute right-0 mt-2 w-48 bg-white border rounded-md shadow-lg',
                contentPadding ? 'p-4' : '',
                classes
            ]">
                <slot name="dropdown-content"></slot>
            </div>
        </Transition>
    </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';

defineOptions({
    name: 'Dropdown'
});
defineProps({
    contentPadding: {
        type: Boolean,
        default: true
    },
    classes: {
        type: String,
        default: ''
    }
});

const isOpen = ref(false);

const toggleDropdown = () => {
    isOpen.value = !isOpen.value;
}

const closeDropdown = () => {
    isOpen.value = false;
}

</script>

// client-react/src/components/ui/Dropdown.tsx
import React, { useState } from "react";
import { motion } from "framer-motion";
import Avatar from "./Avatar";

const Dropdown: React.FC = () => {
    const [isOpen, setIsOpen] = useState(false);

    const toggleDropdown = () => {
        setIsOpen(!isOpen);
    }

    return (
        <div className="relative inline-block text-left">
            <button onClick={toggleDropdown}>
                <Avatar />
            </button>

            {isOpen && (
                <motion.div
                    initial={{ opacity: 0, scale: 0.95 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.95 }}
                    transition={{ duration: 0.2 }}
                    className="absolute right-0 mt-2 w-48 bg-white dark:bg-gray-800 border border-gray-200 dark:border-gray-600 rounded-lg shadow-lg"
                >
                    <a href="#" className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-700">Profile</a>
                    <a href="#" className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-700">Settings</a>
                    <a href="#" className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-700">Logout</a>
                </motion.div>
            )}
        </div>
    );
};

export default Dropdown;
